/// <reference types="@sveltejs/kit" />

interface ImportMetaEnv {
	VITE_ORIGIN: string
	VITE_PRODUCTION_ORIGIN: string
	VITE_ADSENSE_CLIENT: string
	VITE_GITHUB_URL: string
	VITE_ALGOLIA_APP_ID: string
	VITE_ALGOLIA_API_KEY: string
	VITE_FIREBASE_ADMIN_KEY: string
	VITE_FIREBASE_API_KEY: string
	VITE_FIREBASE_AUTH_DOMAIN: string
	VITE_FIREBASE_PROJECT_ID: string
	VITE_FIREBASE_STORAGE_BUCKET: string
	VITE_FIREBASE_MESSAGING_SENDER_ID: string
	VITE_FIREBASE_APP_ID: string
	VITE_FIREBASE_MEASUREMENT_ID: string
	VITE_HASH: string
	VITE_COOKIE_SECRET: string
}

declare const MOBILE: boolean
